# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: yzisis-p <yzisis-p@student.42barcel>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/05/11 17:59:27 by yzisis-p          #+#    #+#              #
#    Updated: 2022/09/14 17:01:23 by yzisis-p         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS	=	ft_isalnum.c 	\
			ft_isprint.c 	\
			ft_memcmp.c  	\
			ft_putchar_fd.c \
 			ft_split.c 		\
			ft_strlcat.c 	\
			ft_strncmp.c 	\
			ft_substr.c 	\
			ft_atoi.c 		\
			ft_isalpha.c 	\
			ft_itoa.c 		\
			ft_memcpy.c		\
			ft_putendl_fd.c \
			ft_strchr.c  	\
			ft_strlcpy.c 	\
			ft_strnstr.c 	\
			ft_tolower.c 	\
			ft_bzero.c   	\
			ft_isascii.c 	\
			ft_memcpy.c 	\
			ft_memmove.c 	\
			ft_putnbr_fd.c  \
			ft_strdup.c  	\
			ft_strlen.c  	\
			ft_strrchr.c 	\
			ft_toupper.c 	\
			ft_calloc.c  	\
			ft_isdigit.c 	\
			ft_memchr.c  	\
			ft_memset.c  	\
			ft_putstr_fd.c  \
			ft_strjoin.c 	\
			ft_strmapi.c 	\
 			ft_strtrim.c	\
			ft_striteri.c

OBJS	= $(SRCS:.c=.o)

BONUS	=	ft_lstadd_back_bonus.c	\
			ft_lstadd_front_bonus.c	\
			ft_lstclear_bonus.c		\
			ft_lstdelone_bonus.c	\
			ft_lstiter_bonus.c		\
			ft_lstlast_bonus.c		\
			ft_lstnew_bonus.c		\
			ft_lstsize_bonus.c		\
			ft_lstmap_bonus.c

BONUS_OBJS	= $(BONUS:.c=.o)

BNS = .bonus

CC			= gcc
RM			= rm -f
CFLAGS		= -Wall -Wextra -Werror -I.

NAME		= libft.a

%.o: %.c libft.h
	gcc $(CFLAGS) -c $< -o $@

all:		$(NAME)

$(NAME):	$(OBJS)
			@ar rcs $(NAME) $(OBJS)
			@echo "Mandatory part compiled!"

clean:
			$(RM) $(OBJS) $(BONUS_OBJS)

fclean:		clean
			$(RM) $(NAME)

re:			fclean $(NAME)

bonus:		$(BNS)

$(BNS):		$(OBJS) $(BONUS_OBJS)
			@ar rcs $(NAME) $(OBJS) $(BONUS_OBJS)
			@touch $@
			@echo "Bonus part compiled!"

.PHONY:		all clean fclean re
